/*
 * Copyright (C) 2026 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// JSC C++ API exposed to WebKit via private headers.

#include <JavaScriptCore/AbortReason.h>
#include <JavaScriptCore/AbstractMacroAssembler.h>
#include <JavaScriptCore/AbstractModuleRecord.h>
#include <JavaScriptCore/AbstractSlotVisitor.h>
#include <JavaScriptCore/AbstractSlotVisitorInlines.h>
#include <JavaScriptCore/AirAllocateRegistersByGraphColoring.h>
#include <JavaScriptCore/AirDisassembler.h>
#include <JavaScriptCore/AirOpcode.h>
#include <JavaScriptCore/AlignedMemoryAllocator.h>
#include <JavaScriptCore/AllocationFailureMode.h>
#include <JavaScriptCore/Allocator.h>
#include <JavaScriptCore/AllocatorForMode.h>
#include <JavaScriptCore/AllocatorInlines.h>
#include <JavaScriptCore/AllowMacroScratchRegisterUsage.h>
#include <JavaScriptCore/AlternateDispatchableAgent.h>
#include <JavaScriptCore/APICast.h>
#include <JavaScriptCore/ArgList.h>
#include <JavaScriptCore/ArgumentsMode.h>
#include <JavaScriptCore/ArithProfile.h>
#include <JavaScriptCore/ArityCheckMode.h>
#include <JavaScriptCore/ARM64Assembler.h>
#include <JavaScriptCore/ARM64EAssembler.h>
#include <JavaScriptCore/ARM64Registers.h>
#include <JavaScriptCore/ARMv7Assembler.h>
#include <JavaScriptCore/ARMv7Registers.h>
#include <JavaScriptCore/ArrayAllocationProfile.h>
#include <JavaScriptCore/ArrayBuffer.h>
#include <JavaScriptCore/ArrayBufferSharingMode.h>
#include <JavaScriptCore/ArrayBufferView.h>
#include <JavaScriptCore/ArrayConstructor.h>
#include <JavaScriptCore/ArrayConventions.h>
#include <JavaScriptCore/ArrayProfile.h>
#include <JavaScriptCore/ArrayPrototype.h>
#include <JavaScriptCore/ArrayStorage.h>
#include <JavaScriptCore/ArrayStorageInlines.h>
#include <JavaScriptCore/AssemblerBuffer.h>
#include <JavaScriptCore/AssemblerCommon.h>
#include <JavaScriptCore/AssemblyComments.h>
#include <JavaScriptCore/AssemblyHelpers.h>
#include <JavaScriptCore/AssemblyHelpersSpoolers.h>
#include <JavaScriptCore/AsyncIteratorPrototype.h>
#include <JavaScriptCore/AsyncStackTrace.h>
#include <JavaScriptCore/AugmentableInspectorController.h>
#include <JavaScriptCore/AugmentableInspectorControllerClient.h>
#include <JavaScriptCore/AuxiliaryBarrier.h>
#include <JavaScriptCore/AuxiliaryBarrierInlines.h>
#include <JavaScriptCore/B3CanonicalizePrePostIncrements.h>
#include <JavaScriptCore/B3Common.h>
#include <JavaScriptCore/B3Compile.h>
#include <JavaScriptCore/B3Type.h>
#include <JavaScriptCore/B3ValueRep.h>
#include <JavaScriptCore/BaselineJITRegisters.h>
#include <JavaScriptCore/BasicBlockLocation.h>
#include <JavaScriptCore/BatchedTransitionOptimizer.h>
#include <JavaScriptCore/BigInt64Array.h>
#include <JavaScriptCore/BigIntConstructor.h>
#include <JavaScriptCore/BigIntObject.h>
#include <JavaScriptCore/BigIntPrototype.h>
#include <JavaScriptCore/BigUint64Array.h>
#include <JavaScriptCore/BinarySwitch.h>
#include <JavaScriptCore/BlockDirectory.h>
#include <JavaScriptCore/BlockDirectoryBits.h>
#include <JavaScriptCore/BlockDirectoryInlines.h>
#include <JavaScriptCore/BooleanObject.h>
#include <JavaScriptCore/BooleanPrototype.h>
#include <JavaScriptCore/BrandedStructure.h>
#include <JavaScriptCore/Breakpoint.h>
#include <JavaScriptCore/BufferMemoryHandle.h>
#include <JavaScriptCore/BuiltinExecutables.h>
#include <JavaScriptCore/BuiltinNames.h>
#include <JavaScriptCore/BuiltinUtils.h>
#include <JavaScriptCore/Butterfly.h>
#include <JavaScriptCore/ButterflyInlines.h>
#include <JavaScriptCore/BytecodeCacheError.h>
#include <JavaScriptCore/BytecodeConventions.h>
#include <JavaScriptCore/BytecodeGeneratorification.h>
#include <JavaScriptCore/BytecodeIndex.h>
#include <JavaScriptCore/BytecodeIntrinsicRegistry.h>
#include <JavaScriptCore/Bytecodes.h>
#include <JavaScriptCore/CacheableIdentifier.h>
#include <JavaScriptCore/CacheableIdentifierInlines.h>
#include <JavaScriptCore/CachedBytecode.h>
#include <JavaScriptCore/CachedCall.h>
#include <JavaScriptCore/CachedCallInlines.h>
#include <JavaScriptCore/CachedTypes.h>
#include <JavaScriptCore/CachePayload.h>
#include <JavaScriptCore/CacheUpdate.h>
#include <JavaScriptCore/CagedBarrierPtr.h>
#include <JavaScriptCore/CallData.h>
#include <JavaScriptCore/CallEdge.h>
#include <JavaScriptCore/CalleeBits.h>
#include <JavaScriptCore/CallFrame.h>
#include <JavaScriptCore/CallFrameInlines.h>
#include <JavaScriptCore/CallFrameShuffleData.h>
#include <JavaScriptCore/CallLinkInfo.h>
#include <JavaScriptCore/CallLinkInfoBase.h>
#include <JavaScriptCore/CallMode.h>
#include <JavaScriptCore/CallVariant.h>
#include <JavaScriptCore/CCallHelpers.h>
#include <JavaScriptCore/CellAttributes.h>
#include <JavaScriptCore/CellContainer.h>
#include <JavaScriptCore/CellContainerInlines.h>
#include <JavaScriptCore/CellState.h>
#include <JavaScriptCore/CheckpointOSRExitSideState.h>
#include <JavaScriptCore/ClassInfo.h>
#include <JavaScriptCore/ClonedArguments.h>
#include <JavaScriptCore/CLoopStack.h>
#include <JavaScriptCore/CLoopStackInlines.h>
#include <JavaScriptCore/CodeBlock.h>
#include <JavaScriptCore/CodeBlockHash.h>
#include <JavaScriptCore/CodeBlockJettisoningWatchpoint.h>
#include <JavaScriptCore/CodeBlockSet.h>
#include <JavaScriptCore/CodeBlockWithJITType.h>
#include <JavaScriptCore/CodeLocation.h>
#include <JavaScriptCore/CodeOrigin.h>
#include <JavaScriptCore/CodeSpecializationKind.h>
#include <JavaScriptCore/CodeType.h>
#include <JavaScriptCore/CollectionScope.h>
#include <JavaScriptCore/CollectorPhase.h>
#include <JavaScriptCore/CommonIdentifiers.h>
#include <JavaScriptCore/CompilationResult.h>
#include <JavaScriptCore/CompleteSubspace.h>
#include <JavaScriptCore/CompleteSubspaceInlines.h>
#include <JavaScriptCore/Completion.h>
#include <JavaScriptCore/ComplexGetStatus.h>
#include <JavaScriptCore/Concurrency.h>
#include <JavaScriptCore/ConcurrentJSLock.h>
#include <JavaScriptCore/config.h>
#include <JavaScriptCore/ConfigFile.h>
#include <JavaScriptCore/ConservativeRoots.h>
#include <JavaScriptCore/ConsoleClient.h>
#include <JavaScriptCore/ConsoleMessage.h>
#include <JavaScriptCore/ConsoleTypes.h>
//#include <JavaScriptCore/ConstantMode.h>
//#include <JavaScriptCore/ConstraintConcurrency.h>
//#include <JavaScriptCore/ConstraintParallelism.h>
//#include <JavaScriptCore/ConstraintVolatility.h>
//#include <JavaScriptCore/ConstructAbility.h>
//#include <JavaScriptCore/ConstructData.h>
//#include <JavaScriptCore/ConstructorKind.h>
#include <JavaScriptCore/ContentSearchUtilities.h>
#include <JavaScriptCore/ControlFlowProfiler.h>
#include <JavaScriptCore/CPU.h>
#include <JavaScriptCore/CrossTaskToken.h>
#include <JavaScriptCore/CustomGetterSetter.h>
#include <JavaScriptCore/DataFormat.h>
#include <JavaScriptCore/DataView.h>
#include <JavaScriptCore/DateInstance.h>
#include <JavaScriptCore/DateInstanceCache.h>
#include <JavaScriptCore/Debugger.h>
#include <JavaScriptCore/DebuggerCallFrame.h>
#include <JavaScriptCore/DebuggerEvalEnabler.h>
#include <JavaScriptCore/DebuggerParseData.h>
#include <JavaScriptCore/DebuggerPrimitives.h>
#include <JavaScriptCore/DeferGC.h>
#include <JavaScriptCore/DeferGCInlines.h>
#include <JavaScriptCore/DeferredCompilationCallback.h>
#include <JavaScriptCore/DeferredSourceDump.h>
#include <JavaScriptCore/DeferredWorkTimer.h>
#include <JavaScriptCore/DeferredWorkTimerInlines.h>
#include <JavaScriptCore/DeferTermination.h>
#include <JavaScriptCore/DefinePropertyAttributes.h>
#include <JavaScriptCore/DeleteAllCodeEffort.h>
#include <JavaScriptCore/DeletePropertySlot.h>
#include <JavaScriptCore/DestructionMode.h>
#include <JavaScriptCore/DFGCodeOriginPool.h>
#include <JavaScriptCore/DFGCommon.h>
#include <JavaScriptCore/DFGDoesGCCheck.h>
#include <JavaScriptCore/DFGExitProfile.h>
#include <JavaScriptCore/DFGMinifiedID.h>
#include <JavaScriptCore/DirectArguments.h>
#include <JavaScriptCore/DirectArgumentsOffset.h>
#include <JavaScriptCore/DirectEvalCodeCache.h>
#include <JavaScriptCore/DirectEvalExecutable.h>
#include <JavaScriptCore/DisallowMacroScratchRegisterUsage.h>
#include <JavaScriptCore/DisallowScope.h>
#include <JavaScriptCore/DisallowVMEntry.h>
#include <JavaScriptCore/Disassembler.h>
//#include <JavaScriptCore/DOMAnnotation.h>
//#include <JavaScriptCore/DOMAttributeGetterSetter.h>
#include <JavaScriptCore/DOMJITAbstractHeap.h>
//#include <JavaScriptCore/DOMJITCallDOMGetterSnippet.h>
//#include <JavaScriptCore/DOMJITEffect.h>
//#include <JavaScriptCore/DOMJITGetterSetter.h>
//#include <JavaScriptCore/DOMJITHeapRange.h>
//#include <JavaScriptCore/DOMJITSignature.h>
#include <JavaScriptCore/DumpContext.h>
#include <JavaScriptCore/ECMAMode.h>
#include <JavaScriptCore/EdenGCActivityCallback.h>
#include <JavaScriptCore/EnsureStillAliveHere.h>
#include <JavaScriptCore/EntryFrame.h>
#include <JavaScriptCore/EnumerationMode.h>
#include <JavaScriptCore/Error.h>
#include <JavaScriptCore/ErrorHandlingScope.h>
#include <JavaScriptCore/ErrorInstance.h>
#include <JavaScriptCore/ErrorPrototype.h>
#include <JavaScriptCore/ErrorType.h>
#include <JavaScriptCore/EvacuatedStack.h>
#include <JavaScriptCore/EvalExecutable.h>
#include <JavaScriptCore/Exception.h>
#include <JavaScriptCore/ExceptionEventLocation.h>
#include <JavaScriptCore/ExceptionExpectation.h>
#include <JavaScriptCore/ExceptionFuzz.h>
#include <JavaScriptCore/ExceptionHelpers.h>
#include <JavaScriptCore/ExceptionScope.h>
#include <JavaScriptCore/ExecutableAllocationFuzz.h>
#include <JavaScriptCore/ExecutableAllocator.h>
#include <JavaScriptCore/ExecutableBase.h>
#include <JavaScriptCore/ExecutableBaseInlines.h>
#include <JavaScriptCore/ExecutableInfo.h>
#include <JavaScriptCore/ExecutableMemoryHandle.h>
#include <JavaScriptCore/ExecutionCounter.h>
#include <JavaScriptCore/ExitingInlineKind.h>
#include <JavaScriptCore/ExitingJITType.h>
#include <JavaScriptCore/ExitKind.h>
#include <JavaScriptCore/ExpressionInfo.h>
#include <JavaScriptCore/ExpressionInfoInlines.h>
#include <JavaScriptCore/FastJITPermissions.h>
#include <JavaScriptCore/FastMallocAlignedMemoryAllocator.h>
#include <JavaScriptCore/Float16Array.h>
#include <JavaScriptCore/Float32Array.h>
#include <JavaScriptCore/Float64Array.h>
#include <JavaScriptCore/Forward.h>
#include <JavaScriptCore/FPRInfo.h>
#include <JavaScriptCore/FrameTracers.h>
#include <JavaScriptCore/FreeList.h>
#include <JavaScriptCore/FreeListInlines.h>
#include <JavaScriptCore/FTLExitArgument.h>
#include <JavaScriptCore/FTLLocation.h>
#include <JavaScriptCore/FTLRecoveryOpcode.h>
#include <JavaScriptCore/FTLSaveRestore.h>
#include <JavaScriptCore/FTLSlowPathCallKey.h>
#include <JavaScriptCore/FullGCActivityCallback.h>
#include <JavaScriptCore/FunctionConstructor.h>
#include <JavaScriptCore/FunctionExecutable.h>
#include <JavaScriptCore/FunctionExecutableDump.h>
#include <JavaScriptCore/FunctionHasExecutedCache.h>
#include <JavaScriptCore/FunctionPrototype.h>
#include <JavaScriptCore/FunctionRareData.h>
#include <JavaScriptCore/FuzzerAgent.h>
#include <JavaScriptCore/Gate.h>
#include <JavaScriptCore/GCActivityCallback.h>
#include <JavaScriptCore/GCAssertions.h>
#include <JavaScriptCore/GCAwareJITStubRoutine.h>
#include <JavaScriptCore/GCConductor.h>
#include <JavaScriptCore/GCDeferralContext.h>
#include <JavaScriptCore/GCIncomingRefCounted.h>
#include <JavaScriptCore/GCIncomingRefCountedInlines.h>
#include <JavaScriptCore/GCIncomingRefCountedSet.h>
#include <JavaScriptCore/GCIncomingRefCountedSetInlines.h>
#include <JavaScriptCore/GCLogging.h>
#include <JavaScriptCore/GCMemoryOperations.h>
#include <JavaScriptCore/GCOwnedDataScope.h>
#include <JavaScriptCore/GCRequest.h>
#include <JavaScriptCore/GCSegmentedArray.h>
#include <JavaScriptCore/GCSegmentedArrayInlines.h>
#include <JavaScriptCore/GdbJIT.h>
#include <JavaScriptCore/GeneratorFunctionConstructor.h>
#include <JavaScriptCore/GeneratorFunctionPrototype.h>
#include <JavaScriptCore/GeneratorPrototype.h>
#include <JavaScriptCore/GenericArgumentsImpl.h>
#include <JavaScriptCore/GenericArgumentsImplInlines.h>
#include <JavaScriptCore/GenericOffset.h>
#include <JavaScriptCore/GenericTypedArrayView.h>
#include <JavaScriptCore/GenericTypedArrayViewInlines.h>
#include <JavaScriptCore/GetPutInfo.h>
#include <JavaScriptCore/GetterSetter.h>
#include <JavaScriptCore/GetVM.h>
#include <JavaScriptCore/GlobalExecutable.h>
#include <JavaScriptCore/GlobalObjectMethodTable.h>
#include <JavaScriptCore/GPRInfo.h>
#include <JavaScriptCore/Handle.h>
#include <JavaScriptCore/HandleBlock.h>
#include <JavaScriptCore/HandleForward.h>
#include <JavaScriptCore/HandlerInfo.h>
#include <JavaScriptCore/HandleSet.h>
#include <JavaScriptCore/HandleTypes.h>
#include <JavaScriptCore/HashMapHelper.h>
#include <JavaScriptCore/HasOwnPropertyCache.h>
#include <JavaScriptCore/Heap.h>
#include <JavaScriptCore/HeapAnalyzer.h>
#include <JavaScriptCore/HeapCell.h>
#include <JavaScriptCore/HeapCellInlines.h>
#include <JavaScriptCore/HeapCellType.h>
#include <JavaScriptCore/HeapFinalizerCallback.h>
#include <JavaScriptCore/HeapInlines.h>
#include <JavaScriptCore/HeapObserver.h>
#include <JavaScriptCore/HeapSnapshot.h>
#include <JavaScriptCore/HeapSnapshotBuilder.h>
#include <JavaScriptCore/ICStatusMap.h>
#include <JavaScriptCore/Identifier.h>
#include <JavaScriptCore/IdentifierInlines.h>
#include <JavaScriptCore/IdentifiersFactory.h>
#include <JavaScriptCore/ImplementationVisibility.h>
#include <JavaScriptCore/ImportMap.h>
#include <JavaScriptCore/IncrementalSweeper.h>
#include <JavaScriptCore/IndexingHeader.h>
#include <JavaScriptCore/IndexingHeaderInlines.h>
#include <JavaScriptCore/IndexingType.h>
#include <JavaScriptCore/IndirectEvalExecutable.h>
#include <JavaScriptCore/InferredValue.h>
#include <JavaScriptCore/InitializeThreading.h>
#include <JavaScriptCore/InjectedScript.h>
#include <JavaScriptCore/InjectedScriptBase.h>
#include <JavaScriptCore/InjectedScriptHost.h>
#include <JavaScriptCore/InjectedScriptManager.h>
#include <JavaScriptCore/InjectedScriptModule.h>
#include <JavaScriptCore/InlineAttribute.h>
#include <JavaScriptCore/InlineCallFrame.h>
#include <JavaScriptCore/InlineCallFrameSet.h>
#include <JavaScriptCore/InspectorAgent.h>
#include <JavaScriptCore/InspectorAgentBase.h>
#include <JavaScriptCore/InspectorAgentRegistry.h>
#include <JavaScriptCore/InspectorAlternateBackendDispatchers.h>
#include <JavaScriptCore/InspectorAuditAgent.h>
#include <JavaScriptCore/InspectorBackendDispatcher.h>
#include <JavaScriptCore/InspectorBackendDispatchers.h>
#include <JavaScriptCore/InspectorConsoleAgent.h>
#include <JavaScriptCore/InspectorDebuggerAgent.h>
#include <JavaScriptCore/InspectorEnvironment.h>
#include <JavaScriptCore/InspectorFrontendChannel.h>
#include <JavaScriptCore/InspectorFrontendDispatchers.h>
#include <JavaScriptCore/InspectorFrontendRouter.h>
#include <JavaScriptCore/InspectorHeapAgent.h>
#include <JavaScriptCore/InspectorProtocolObjects.h>
#include <JavaScriptCore/InspectorProtocolTypes.h>
#include <JavaScriptCore/InspectorRuntimeAgent.h>
#include <JavaScriptCore/InspectorScriptProfilerAgent.h>
#include <JavaScriptCore/InspectorTarget.h>
#include <JavaScriptCore/InspectorTargetAgent.h>
#include <JavaScriptCore/Instruction.h>
#include <JavaScriptCore/InstructionStream.h>
#include <JavaScriptCore/Int16Array.h>
#include <JavaScriptCore/Int32Array.h>
#include <JavaScriptCore/Int8Array.h>
#include <JavaScriptCore/Integrity.h>
#include <JavaScriptCore/IntegrityInlines.h>
#include <JavaScriptCore/InternalFunction.h>
#include <JavaScriptCore/InternalFunctionAllocationProfile.h>
#include <JavaScriptCore/Interpreter.h>
#include <JavaScriptCore/IntlObject.h>
#include <JavaScriptCore/Intrinsic.h>
#include <JavaScriptCore/IsoCellSet.h>
#include <JavaScriptCore/IsoHeapCellType.h>
#include <JavaScriptCore/IsoInlinedHeapCellType.h>
#include <JavaScriptCore/IsoSubspace.h>
#include <JavaScriptCore/IsoSubspaceInlines.h>
#include <JavaScriptCore/IterationKind.h>
#include <JavaScriptCore/IterationModeMetadata.h>
#include <JavaScriptCore/IteratorOperations.h>
#include <JavaScriptCore/JITAllocator.h>
#include <JavaScriptCore/JITCode.h>
#include <JavaScriptCore/JITCodeMap.h>
#include <JavaScriptCore/JITCompilation.h>
#include <JavaScriptCore/JITCompilationEffort.h>
#include <JavaScriptCore/JITCompilationMode.h>
#include <JavaScriptCore/JITExceptions.h>
#include <JavaScriptCore/JITMathICForwards.h>
#include <JavaScriptCore/JITOperationList.h>
#include <JavaScriptCore/JITOperations.h>
#include <JavaScriptCore/JITOperationValidation.h>
#include <JavaScriptCore/JITStubRoutine.h>
#include <JavaScriptCore/JITStubRoutineSet.h>
#include <JavaScriptCore/JSAPIValueWrapper.h>
#include <JavaScriptCore/JSArray.h>
#include <JavaScriptCore/JSArrayBuffer.h>
#include <JavaScriptCore/JSArrayBufferConstructor.h>
#include <JavaScriptCore/JSArrayBufferPrototype.h>
#include <JavaScriptCore/JSArrayBufferView.h>
#include <JavaScriptCore/JSArrayBufferViewInlines.h>
#include <JavaScriptCore/JSArrayInlines.h>
#include <JavaScriptCore/JSArrayIterator.h>
#include <JavaScriptCore/JSBigInt.h>
#include <JavaScriptCore/JSBigIntInlines.h>
#include <JavaScriptCore/JSBoundFunction.h>
#include <JavaScriptCore/JSCallee.h>
#include <JavaScriptCore/JSCalleeInlines.h>
#include <JavaScriptCore/JSCast.h>
#include <JavaScriptCore/JSCBuiltins.h>
#include <JavaScriptCore/JSCBytecodeCacheVersion.h>
#include <JavaScriptCore/JSCConfig.h>
#include <JavaScriptCore/JSCell.h>
#include <JavaScriptCore/JSCellButterfly.h>
#include <JavaScriptCore/JSCellInlines.h>
#include <JavaScriptCore/JSCInlines.h>
#include <JavaScriptCore/JSCJSValue.h>
#include <JavaScriptCore/JSCJSValueCellInlines.h>
#include <JavaScriptCore/JSCJSValueInlines.h>
#include <JavaScriptCore/JSClassRef.h>
#include <JavaScriptCore/JSContextInternal.h>
#include <JavaScriptCore/JSContextRefInspectorSupport.h>
#include <JavaScriptCore/JSCPtrTag.h>
#include <JavaScriptCore/JSCTestRunnerUtils.h>
#include <JavaScriptCore/JSCustomGetterFunction.h>
#include <JavaScriptCore/JSCustomSetterFunction.h>
#include <JavaScriptCore/JSDataView.h>
#include <JavaScriptCore/JSDataViewPrototype.h>
#include <JavaScriptCore/JSDateMath.h>
#include <JavaScriptCore/JSDestructibleObject.h>
#include <JavaScriptCore/JSDestructibleObjectHeapCellType.h>
#include <JavaScriptCore/JSDollarVM.h>
#include <JavaScriptCore/JSExportMacros.h>
#include <JavaScriptCore/JSFloat16Array.h>
#include <JavaScriptCore/JSFloat32Array.h>
#include <JavaScriptCore/JSFloat64Array.h>
#include <JavaScriptCore/JSFunction.h>
#include <JavaScriptCore/JSFunctionInlines.h>
#include <JavaScriptCore/JSFunctionWithFields.h>
#include <JavaScriptCore/JSGenerator.h>
#include <JavaScriptCore/JSGeneratorFunction.h>
#include <JavaScriptCore/JSGenericTypedArrayView.h>
#include <JavaScriptCore/JSGenericTypedArrayViewConstructor.h>
#include <JavaScriptCore/JSGenericTypedArrayViewInlines.h>
#include <JavaScriptCore/JSGenericTypedArrayViewPrototype.h>
#include <JavaScriptCore/JSGenericTypedArrayViewPrototypeInlines.h>
#include <JavaScriptCore/JSGlobalLexicalEnvironment.h>
#include <JavaScriptCore/JSGlobalObject.h>
#include <JavaScriptCore/JSGlobalObjectFunctions.h>
#include <JavaScriptCore/JSGlobalObjectInlines.h>
#include <JavaScriptCore/JSGlobalProxy.h>
#include <JavaScriptCore/JSGlobalProxyInlines.h>
#include <JavaScriptCore/JSHeapDouble.h>
#include <JavaScriptCore/JSHeapInt32.h>
#include <JavaScriptCore/JSInt16Array.h>
#include <JavaScriptCore/JSInt32Array.h>
#include <JavaScriptCore/JSInt8Array.h>
#include <JavaScriptCore/JSInterfaceJIT.h>
#include <JavaScriptCore/JSInternalFieldObjectImpl.h>
#include <JavaScriptCore/JSInternalPromise.h>
#include <JavaScriptCore/JSInternalPromiseConstructor.h>
#include <JavaScriptCore/JSIteratorPrototype.h>
#include <JavaScriptCore/JSLexicalEnvironment.h>
#include <JavaScriptCore/JSLock.h>
#include <JavaScriptCore/JSMap.h>
#include <JavaScriptCore/JSMapInlines.h>
#include <JavaScriptCore/JSMapIterator.h>
#include <JavaScriptCore/JSMicrotask.h>
#include <JavaScriptCore/JSMicrotaskDispatcher.h>
#include <JavaScriptCore/JSModuleEnvironment.h>
#include <JavaScriptCore/JSModuleNamespaceObject.h>
#include <JavaScriptCore/JSModuleRecord.h>
#include <JavaScriptCore/JSNativeStdFunction.h>
#include <JavaScriptCore/JSObject.h>
#include <JavaScriptCore/JSObjectInlines.h>
#include <JavaScriptCore/JSONAtomStringCache.h>
#include <JavaScriptCore/JSONObject.h>
#include <JavaScriptCore/JSPIContext.h>
#include <JavaScriptCore/JSPIContextInlines.h>
#include <JavaScriptCore/JSPromise.h>
#include <JavaScriptCore/JSPromiseConstructor.h>
#include <JavaScriptCore/JSPropertyNameEnumerator.h>
#include <JavaScriptCore/JSRemoteFunction.h>
#include <JavaScriptCore/JSRetainPtr.h>
#include <JavaScriptCore/JSRunLoopTimer.h>
#include <JavaScriptCore/JSScope.h>
#include <JavaScriptCore/JSScriptFetcher.h>
#include <JavaScriptCore/JSScriptFetchParameters.h>
#include <JavaScriptCore/JSSegmentedVariableObject.h>
#include <JavaScriptCore/JSSet.h>
#include <JavaScriptCore/JSSetInlines.h>
#include <JavaScriptCore/JSSetIterator.h>
#include <JavaScriptCore/JSSourceCode.h>
#include <JavaScriptCore/JSString.h>
#include <JavaScriptCore/JSStringInlines.h>
#include <JavaScriptCore/JSStringIterator.h>
#include <JavaScriptCore/JSSymbolTableObject.h>
#include <JavaScriptCore/JSTemplateObjectDescriptor.h>
#include <JavaScriptCore/JSType.h>
#include <JavaScriptCore/JSTypedArrayConstructors.h>
#include <JavaScriptCore/JSTypedArrayPrototypes.h>
#include <JavaScriptCore/JSTypedArrays.h>
#include <JavaScriptCore/JSTypedArrayViewPrototype.h>
#include <JavaScriptCore/JSTypeInfo.h>
#include <JavaScriptCore/JSUint16Array.h>
#include <JavaScriptCore/JSUint32Array.h>
#include <JavaScriptCore/JSUint8Array.h>
#include <JavaScriptCore/JSUint8ClampedArray.h>
#include <JavaScriptCore/JSValueInternal.h>
#include <JavaScriptCore/JSVirtualMachineInternal.h>
#include <JavaScriptCore/JSWeakObjectMapRefInternal.h>
#include <JavaScriptCore/JSWeakValue.h>
#include <JavaScriptCore/JSWebAssembly.h>
#include <JavaScriptCore/JSWebAssemblyGlobal.h>
#include <JavaScriptCore/JSWebAssemblyInstance.h>
#include <JavaScriptCore/JSWebAssemblyLinkError.h>
#include <JavaScriptCore/JSWebAssemblyMemory.h>
#include <JavaScriptCore/JSWebAssemblyModule.h>
#include <JavaScriptCore/JSWebAssemblyTable.h>
#include <JavaScriptCore/JSWithScope.h>
#include <JavaScriptCore/JSWrapperObject.h>
#include <JavaScriptCore/JumpTable.h>
#include <JavaScriptCore/KeyAtomStringCache.h>
#include <JavaScriptCore/KeyAtomStringCacheInlines.h>
#include <JavaScriptCore/LazyClassStructure.h>
#include <JavaScriptCore/LazyOperandValueProfile.h>
#include <JavaScriptCore/LazyProperty.h>
#include <JavaScriptCore/LazyValueProfile.h>
#include <JavaScriptCore/LeafExecutable.h>
#include <JavaScriptCore/Lexer.h>
#include <JavaScriptCore/LexerUnicodeProperties.h>
#include <JavaScriptCore/LineColumn.h>
#include <JavaScriptCore/LinkBuffer.h>
#include <JavaScriptCore/LinkTimeConstant.h>
#include <JavaScriptCore/LLIntCommon.h>
#include <JavaScriptCore/LLIntEntrypoint.h>
#include <JavaScriptCore/LLIntExceptions.h>
#include <JavaScriptCore/LLIntOpcode.h>
#include <JavaScriptCore/LLIntThunks.h>
#include <JavaScriptCore/LLVMProfiling.h>
#include <JavaScriptCore/LocalAllocator.h>
#include <JavaScriptCore/LocalAllocatorInlines.h>
#include <JavaScriptCore/Lookup.h>
#include <JavaScriptCore/MachineStackMarker.h>
#include <JavaScriptCore/MacroAssembler.h>
#include <JavaScriptCore/MacroAssemblerARM64.h>
#include <JavaScriptCore/MacroAssemblerARM64E.h>
#include <JavaScriptCore/MacroAssemblerARMv7.h>
#include <JavaScriptCore/MacroAssemblerCodeRef.h>
#include <JavaScriptCore/MacroAssemblerHelpers.h>
#include <JavaScriptCore/MacroAssemblerPrinter.h>
#include <JavaScriptCore/MacroAssemblerX86_64.h>
#include <JavaScriptCore/MapIteratorPrototype.h>
#include <JavaScriptCore/MapIteratorPrototypeInlines.h>
#include <JavaScriptCore/MarkedBlock.h>
#include <JavaScriptCore/MarkedBlockInlines.h>
#include <JavaScriptCore/MarkedBlockSet.h>
#include <JavaScriptCore/MarkedSpace.h>
#include <JavaScriptCore/MarkedSpaceInlines.h>
#include <JavaScriptCore/MarkedVector.h>
#include <JavaScriptCore/MarkingConstraint.h>
#include <JavaScriptCore/MarkStack.h>
#include <JavaScriptCore/MatchResult.h>
#include <JavaScriptCore/MathCommon.h>
#include <JavaScriptCore/MathObject.h>
#include <JavaScriptCore/MaxFrameExtentForSlowPathCall.h>
#include <JavaScriptCore/MegamorphicCache.h>
#include <JavaScriptCore/MemoryMode.h>
#include <JavaScriptCore/MemoryStatistics.h>
#include <JavaScriptCore/MetadataTable.h>
#include <JavaScriptCore/Microtask.h>
#include <JavaScriptCore/MicrotaskCall.h>
#include <JavaScriptCore/MicrotaskCallInlines.h>
#include <JavaScriptCore/MicrotaskQueue.h>
#include <JavaScriptCore/MicrotaskQueueInlines.h>
#include <JavaScriptCore/ModuleProgramExecutable.h>
#include <JavaScriptCore/ModuleScopeData.h>
#include <JavaScriptCore/MutatorState.h>
#include <JavaScriptCore/NativeCallee.h>
#include <JavaScriptCore/NativeCalleeRegistry.h>
#include <JavaScriptCore/NativeExecutable.h>
#include <JavaScriptCore/NativeFunction.h>
#include <JavaScriptCore/NullGetterFunction.h>
#include <JavaScriptCore/NullSetterFunction.h>
#include <JavaScriptCore/NumberObject.h>
#include <JavaScriptCore/NumberPrototype.h>
#include <JavaScriptCore/NumericStrings.h>
#include <JavaScriptCore/ObjectAdaptiveStructureWatchpoint.h>
#include <JavaScriptCore/ObjectAllocationProfile.h>
#include <JavaScriptCore/ObjectConstructor.h>
#include <JavaScriptCore/ObjectInitializationScope.h>
#include <JavaScriptCore/ObjectPropertyCondition.h>
#include <JavaScriptCore/ObjectPropertyConditionSet.h>
#include <JavaScriptCore/ObjectPrototype.h>
#include <JavaScriptCore/OpaqueJSString.h>
#include <JavaScriptCore/Opcode.h>
#include <JavaScriptCore/OpcodeSize.h>
#include <JavaScriptCore/Operands.h>
#include <JavaScriptCore/OperandsInlines.h>
#include <JavaScriptCore/OperationResult.h>
#include <JavaScriptCore/Operations.h>
#include <JavaScriptCore/Options.h>
#include <JavaScriptCore/OptionsList.h>
#include <JavaScriptCore/OrderedHashTable.h>
#include <JavaScriptCore/OrderedHashTableHelper.h>
#include <JavaScriptCore/OSCheck.h>
#include <JavaScriptCore/PackedCellPtr.h>
#include <JavaScriptCore/PageCount.h>
#include <JavaScriptCore/ParseHash.h>
#include <JavaScriptCore/ParseInt.h>
#include <JavaScriptCore/ParserArena.h>
#include <JavaScriptCore/ParserError.h>
#include <JavaScriptCore/ParserModes.h>
#include <JavaScriptCore/ParserTokens.h>
#include <JavaScriptCore/PCToCodeOriginMap.h>
#include <JavaScriptCore/PerGlobalObjectWrapperWorld.h>
#include <JavaScriptCore/PinballCompletion.h>
#include <JavaScriptCore/PinballHandlerContext.h>
#include <JavaScriptCore/PolymorphicCallStubRoutine.h>
#include <JavaScriptCore/PolyProtoAccessChain.h>
#include <JavaScriptCore/PreciseAllocation.h>
#include <JavaScriptCore/PreciseJumpTargets.h>
#include <JavaScriptCore/PreciseSubspace.h>
#include <JavaScriptCore/Printer.h>
#include <JavaScriptCore/PrivateFieldPutKind.h>
#include <JavaScriptCore/PrivateName.h>
#include <JavaScriptCore/ProbeContext.h>
#include <JavaScriptCore/ProbeStack.h>
#include <JavaScriptCore/ProfilerBytecode.h>
#include <JavaScriptCore/ProfilerBytecodes.h>
#include <JavaScriptCore/ProfilerBytecodeSequence.h>
#include <JavaScriptCore/ProfilerCompilation.h>
#include <JavaScriptCore/ProfilerCompilationKind.h>
#include <JavaScriptCore/ProfilerCompiledBytecode.h>
#include <JavaScriptCore/ProfilerDatabase.h>
#include <JavaScriptCore/ProfilerEvent.h>
#include <JavaScriptCore/ProfilerExecutionCounter.h>
#include <JavaScriptCore/ProfilerJettisonReason.h>
#include <JavaScriptCore/ProfilerOrigin.h>
#include <JavaScriptCore/ProfilerOriginStack.h>
#include <JavaScriptCore/ProfilerOSRExit.h>
#include <JavaScriptCore/ProfilerOSRExitSite.h>
#include <JavaScriptCore/ProfilerProfiledBytecodes.h>
#include <JavaScriptCore/ProfilerSupport.h>
#include <JavaScriptCore/ProfilerUID.h>
#include <JavaScriptCore/ProgramExecutable.h>
#include <JavaScriptCore/PropertyCondition.h>
#include <JavaScriptCore/PropertyDescriptor.h>
#include <JavaScriptCore/PropertyName.h>
#include <JavaScriptCore/PropertyNameArray.h>
#include <JavaScriptCore/PropertyOffset.h>
#include <JavaScriptCore/PropertySlot.h>
#include <JavaScriptCore/PropertyStorage.h>
#include <JavaScriptCore/PropertyTable.h>
#include <JavaScriptCore/Protect.h>
#include <JavaScriptCore/ProtoCallFrame.h>
#include <JavaScriptCore/ProtoCallFrameInlines.h>
#include <JavaScriptCore/PrototypeKey.h>
#include <JavaScriptCore/ProxyConstructor.h>
#include <JavaScriptCore/ProxyObject.h>
#include <JavaScriptCore/ProxyRevoke.h>
#include <JavaScriptCore/PureNaN.h>
#include <JavaScriptCore/PutByIdFlags.h>
#include <JavaScriptCore/PutDirectIndexMode.h>
#include <JavaScriptCore/PutPropertySlot.h>
#include <JavaScriptCore/ReduceWhitespace.h>
#include <JavaScriptCore/ReflectObject.h>
#include <JavaScriptCore/Reg.h>
#include <JavaScriptCore/RegExp.h>
#include <JavaScriptCore/RegExpCache.h>
#include <JavaScriptCore/RegExpCachedResult.h>
#include <JavaScriptCore/RegExpGlobalData.h>
#include <JavaScriptCore/RegExpKey.h>
#include <JavaScriptCore/RegExpObject.h>
#include <JavaScriptCore/RegExpSubstringGlobalAtomCache.h>
#include <JavaScriptCore/Register.h>
#include <JavaScriptCore/RegisterAtOffset.h>
#include <JavaScriptCore/RegisterAtOffsetList.h>
#include <JavaScriptCore/RegisterInfo.h>
#include <JavaScriptCore/RegisterInlines.h>
#include <JavaScriptCore/RegisterMap.h>
#include <JavaScriptCore/RegisterSet.h>
#include <JavaScriptCore/RegisterState.h>
#include <JavaScriptCore/RegularExpression.h>
#include <JavaScriptCore/RemoteAutomationTarget.h>
#include <JavaScriptCore/RemoteConnectionToTarget.h>
#include <JavaScriptCore/RemoteControllableTarget.h>
#include <JavaScriptCore/RemoteInspectionTarget.h>
#include <JavaScriptCore/RemoteInspector.h>
#include <JavaScriptCore/RemoteInspectorConstants.h>
#include <JavaScriptCore/RemoteInspectorXPCConnection.h>
#include <JavaScriptCore/ResourceExhaustion.h>
#include <JavaScriptCore/ResultType.h>
#include <JavaScriptCore/RootMarkReason.h>
#include <JavaScriptCore/RunningScope.h>
#include <JavaScriptCore/RuntimeFlags.h>
#include <JavaScriptCore/RuntimeType.h>
#include <JavaScriptCore/SamplingCounter.h>
#include <JavaScriptCore/SamplingProfiler.h>
#include <JavaScriptCore/ScopedArguments.h>
#include <JavaScriptCore/ScopedArgumentsTable.h>
#include <JavaScriptCore/ScopeOffset.h>
#include <JavaScriptCore/ScratchRegisterAllocator.h>
#include <JavaScriptCore/Scribble.h>
#include <JavaScriptCore/ScriptArguments.h>
#include <JavaScriptCore/ScriptCallFrame.h>
#include <JavaScriptCore/ScriptCallStack.h>
#include <JavaScriptCore/ScriptCallStackFactory.h>
#include <JavaScriptCore/ScriptExecutable.h>
#include <JavaScriptCore/ScriptFetcher.h>
#include <JavaScriptCore/ScriptFetchParameters.h>
#include <JavaScriptCore/ScriptFunctionCall.h>
#include <JavaScriptCore/ScriptProfilingScope.h>
#include <JavaScriptCore/SecureARM64EHashPins.h>
#include <JavaScriptCore/SecureARM64EHashPinsInlines.h>
#include <JavaScriptCore/SetIteratorPrototype.h>
#include <JavaScriptCore/SetIteratorPrototypeInlines.h>
#include <JavaScriptCore/ShadowChicken.h>
#include <JavaScriptCore/ShadowChickenInlines.h>
#include <JavaScriptCore/ShadowRealmConstructor.h>
#include <JavaScriptCore/ShadowRealmObject.h>
#include <JavaScriptCore/ShadowRealmPrototype.h>
#include <JavaScriptCore/SideDataRepository.h>
#include <JavaScriptCore/SIMDInfo.h>
#include <JavaScriptCore/SimpleRegisterAllocator.h>
#include <JavaScriptCore/SimpleTypedArrayController.h>
#include <JavaScriptCore/SlotVisitor.h>
#include <JavaScriptCore/SlotVisitorInlines.h>
#include <JavaScriptCore/SlotVisitorMacros.h>
#include <JavaScriptCore/SlowPathFunction.h>
#include <JavaScriptCore/SmallStrings.h>
#include <JavaScriptCore/Snippet.h>
#include <JavaScriptCore/SnippetParams.h>
#include <JavaScriptCore/SnippetReg.h>
#include <JavaScriptCore/SnippetSlowPathCalls.h>
#include <JavaScriptCore/SourceCode.h>
#include <JavaScriptCore/SourceID.h>
#include <JavaScriptCore/SourceOrigin.h>
#include <JavaScriptCore/SourceProfiler.h>
#include <JavaScriptCore/SourceProvider.h>
#include <JavaScriptCore/SourceProviderCache.h>
#include <JavaScriptCore/SourceProviderCacheItem.h>
#include <JavaScriptCore/SourceTaintedOrigin.h>
#include <JavaScriptCore/SparseArrayValueMap.h>
#include <JavaScriptCore/SpeculatedType.h>
#include <JavaScriptCore/StableSort.h>
#include <JavaScriptCore/StackAlignment.h>
#include <JavaScriptCore/StackFrame.h>
#include <JavaScriptCore/StackManager.h>
#include <JavaScriptCore/StackManagerInlines.h>
#include <JavaScriptCore/StackVisitor.h>
#include <JavaScriptCore/StaticPropertyAnalysis.h>
#include <JavaScriptCore/StopTheWorldCallback.h>
#include <JavaScriptCore/StringIteratorPrototype.h>
#include <JavaScriptCore/StringObject.h>
#include <JavaScriptCore/StringPrototype.h>
#include <JavaScriptCore/StringReplaceCache.h>
#include <JavaScriptCore/StringSplitCache.h>
#include <JavaScriptCore/Strong.h>
#include <JavaScriptCore/StrongForward.h>
#include <JavaScriptCore/StrongInlines.h>
#include <JavaScriptCore/Structure.h>
#include <JavaScriptCore/StructureCache.h>
#include <JavaScriptCore/StructureChain.h>
#include <JavaScriptCore/StructureID.h>
#include <JavaScriptCore/StructureInlines.h>
#include <JavaScriptCore/StructureRareData.h>
#include <JavaScriptCore/StructureRareDataInlines.h>
#include <JavaScriptCore/StructureSet.h>
#include <JavaScriptCore/StructureTransitionTable.h>
#include <JavaScriptCore/Subspace.h>
#include <JavaScriptCore/SubspaceAccess.h>
#include <JavaScriptCore/SubspaceInlines.h>
#include <JavaScriptCore/SuperSampler.h>
#include <JavaScriptCore/Symbol.h>
#include <JavaScriptCore/SymbolConstructor.h>
#include <JavaScriptCore/SymbolObject.h>
#include <JavaScriptCore/SymbolPrototype.h>
#include <JavaScriptCore/SymbolTable.h>
#include <JavaScriptCore/SymbolTableOrScopeDepth.h>
#include <JavaScriptCore/Synchronousness.h>
#include <JavaScriptCore/SyntheticModuleRecord.h>
#include <JavaScriptCore/TagRegistersMode.h>
#include <JavaScriptCore/TargetAssemblerDefinitions.h>
#include <JavaScriptCore/TemplateObjectDescriptor.h>
#include <JavaScriptCore/TestRunnerUtils.h>
#include <JavaScriptCore/ThrowScope.h>
#include <JavaScriptCore/ThunkGenerator.h>
#include <JavaScriptCore/TinyBloomFilter.h>
#include <JavaScriptCore/ToNativeFromValue.h>
#include <JavaScriptCore/TopExceptionScope.h>
#include <JavaScriptCore/ToThisStatus.h>
#include <JavaScriptCore/TypedArrayAdaptersForwardDeclarations.h>
#include <JavaScriptCore/TypedArrayAdaptors.h>
#include <JavaScriptCore/TypedArrayController.h>
#include <JavaScriptCore/TypedArrayInlines.h>
#include <JavaScriptCore/TypedArrays.h>
#include <JavaScriptCore/TypedArrayType.h>
#include <JavaScriptCore/TypeError.h>
#include <JavaScriptCore/TypeInfoBlob.h>
#include <JavaScriptCore/TypeLocation.h>
#include <JavaScriptCore/TypeLocationCache.h>
#include <JavaScriptCore/TypeofType.h>
#include <JavaScriptCore/TypeProfiler.h>
#include <JavaScriptCore/TypeProfilerLog.h>
#include <JavaScriptCore/TypeSet.h>
#include <JavaScriptCore/UGPRPair.h>
#include <JavaScriptCore/Uint16Array.h>
#include <JavaScriptCore/Uint32Array.h>
#include <JavaScriptCore/Uint8Array.h>
#include <JavaScriptCore/Uint8ClampedArray.h>
#include <JavaScriptCore/UnlinkedCodeBlock.h>
#include <JavaScriptCore/UnlinkedEvalCodeBlock.h>
#include <JavaScriptCore/UnlinkedFunctionCodeBlock.h>
#include <JavaScriptCore/UnlinkedFunctionExecutable.h>
#include <JavaScriptCore/UnlinkedGlobalCodeBlock.h>
#include <JavaScriptCore/UnlinkedMetadataTable.h>
#include <JavaScriptCore/UnlinkedModuleProgramCodeBlock.h>
#include <JavaScriptCore/UnlinkedProgramCodeBlock.h>
#include <JavaScriptCore/UnlinkedSourceCode.h>
#include <JavaScriptCore/ValueProfile.h>
#include <JavaScriptCore/ValueRecovery.h>
#include <JavaScriptCore/VariableEnvironment.h>
#include <JavaScriptCore/VariableWriteFireDetail.h>
#include <JavaScriptCore/VarOffset.h>
#include <JavaScriptCore/VerifierSlotVisitor.h>
#include <JavaScriptCore/VerifierSlotVisitorScope.h>
#include <JavaScriptCore/VirtualRegister.h>
#include <JavaScriptCore/VisitRaceKey.h>
#include <JavaScriptCore/VM.h>
#include <JavaScriptCore/VMEntryRecord.h>
#include <JavaScriptCore/VMEntryScope.h>
#include <JavaScriptCore/VMEntryScopeInlines.h>
#include <JavaScriptCore/VMInlines.h>
#include <JavaScriptCore/VMManager.h>
#include <JavaScriptCore/VMThreadContext.h>
#include <JavaScriptCore/VMTraps.h>
#include <JavaScriptCore/VMTrapsInlines.h>
#include <JavaScriptCore/WaiterListManager.h>
#include <JavaScriptCore/WasmAddressType.h>
#include <JavaScriptCore/WasmBaselineData.h>
#include <JavaScriptCore/WasmBranchHints.h>
#include <JavaScriptCore/WasmCallee.h>
#include <JavaScriptCore/WasmCalleeGroup.h>
#include <JavaScriptCore/WasmCallingConvention.h>
#include <JavaScriptCore/WasmCallProfile.h>
#include <JavaScriptCore/WasmCapabilities.h>
#include <JavaScriptCore/WasmCompilationMode.h>
#include <JavaScriptCore/WasmContext.h>
#include <JavaScriptCore/WasmCreationMode.h>
#include <JavaScriptCore/WasmDebugServer.h>
#include <JavaScriptCore/WasmDebugServerUtilities.h>
#include <JavaScriptCore/WasmExceptionType.h>
#include <JavaScriptCore/WasmFaultSignalHandler.h>
#include <JavaScriptCore/WasmFormat.h>
#include <JavaScriptCore/WasmFunctionIPIntMetadataGenerator.h>
#include <JavaScriptCore/WasmGDBPacketParser.h>
#include <JavaScriptCore/WasmGlobal.h>
#include <JavaScriptCore/WasmHandlerInfo.h>
#include <JavaScriptCore/WasmIndexOrName.h>
#include <JavaScriptCore/WasmInstanceAnchor.h>
#include <JavaScriptCore/WasmIPIntGenerator.h>
#include <JavaScriptCore/WasmIPIntTierUpCounter.h>
#include <JavaScriptCore/WasmJS.h>
#include <JavaScriptCore/WasmLimits.h>
#include <JavaScriptCore/WasmMemory.h>
#include <JavaScriptCore/WasmMemoryInformation.h>
#include <JavaScriptCore/WasmModule.h>
#include <JavaScriptCore/WasmModuleDebugInfo.h>
#include <JavaScriptCore/WasmModuleInformation.h>
#include <JavaScriptCore/WasmName.h>
#include <JavaScriptCore/WasmNameSection.h>
#include <JavaScriptCore/WasmOpcodeOrigin.h>
#include <JavaScriptCore/WasmOps.h>
#include <JavaScriptCore/WasmOSREntryData.h>
#include <JavaScriptCore/WasmSections.h>
#include <JavaScriptCore/WasmSIMDOpcodes.h>
#include <JavaScriptCore/WasmStreamingCompiler.h>
#include <JavaScriptCore/WasmStreamingParser.h>
#include <JavaScriptCore/WasmTable.h>
#include <JavaScriptCore/WasmThunks.h>
#include <JavaScriptCore/WasmTierUpCount.h>
#include <JavaScriptCore/WasmTypeDefinition.h>
#include <JavaScriptCore/WasmTypeDefinitionInlines.h>
#include <JavaScriptCore/WasmValueLocation.h>
#include <JavaScriptCore/WasmVirtualAddress.h>
#include <JavaScriptCore/Watchdog.h>
#include <JavaScriptCore/Watchpoint.h>
#include <JavaScriptCore/Weak.h>
#include <JavaScriptCore/WeakBlock.h>
#include <JavaScriptCore/WeakGCHashTable.h>
#include <JavaScriptCore/WeakGCMap.h>
#include <JavaScriptCore/WeakGCMapInlines.h>
#include <JavaScriptCore/WeakGCSet.h>
#include <JavaScriptCore/WeakGCSetInlines.h>
#include <JavaScriptCore/WeakHandleOwner.h>
#include <JavaScriptCore/WeakImpl.h>
#include <JavaScriptCore/WeakInlines.h>
#include <JavaScriptCore/WeakSet.h>
#include <JavaScriptCore/WeakSetConstructor.h>
#include <JavaScriptCore/WeakSetInlines.h>
#include <JavaScriptCore/WeakSetPrototype.h>
#include <JavaScriptCore/WebAssemblyBuiltin.h>
#include <JavaScriptCore/WebAssemblyCompileOptions.h>
#include <JavaScriptCore/WebAssemblyFunction.h>
#include <JavaScriptCore/WebAssemblyFunctionBase.h>
#include <JavaScriptCore/WebAssemblyGCStructure.h>
#include <JavaScriptCore/WebAssemblyLinkErrorConstructor.h>
#include <JavaScriptCore/WebAssemblyLinkErrorPrototype.h>
#include <JavaScriptCore/WebAssemblyModuleRecord.h>
#include <JavaScriptCore/WebAssemblyWrapperFunction.h>
#include <JavaScriptCore/Width.h>
#include <JavaScriptCore/WriteBarrier.h>
#include <JavaScriptCore/WriteBarrierInlines.h>
#include <JavaScriptCore/WriteBarrierSupport.h>
#include <JavaScriptCore/X86_64Registers.h>
#include <JavaScriptCore/X86Assembler.h>
#include <JavaScriptCore/Yarr.h>
#include <JavaScriptCore/YarrErrorCode.h>
#include <JavaScriptCore/YarrFlags.h>
#include <JavaScriptCore/YarrInterpreter.h>
#include <JavaScriptCore/YarrJIT.h>
#include <JavaScriptCore/YarrJITRegisters.h>
#include <JavaScriptCore/YarrMatchingContextHolder.h>
#include <JavaScriptCore/YarrParser.h>
#include <JavaScriptCore/YarrPattern.h>
#include <JavaScriptCore/YarrUnicodeProperties.h>
