
import argparse
import json
import re
import plistlib
import sqlite3
import subprocess
import typing

from . import objdump

SCHEMA_VERSION = 1

class sdkdb:
    def __init__(self, db_file: typing.Optional[str] = None):
        self.con = sqlite3.connect(':memory:')
        if db_file is None:
            _initialize_db(self.con)
        else:
            cached = sqlite3.connect(db_file)
            cur = cached.execute('SELECT value FROM meta WHERE key = "version"')
            row = cur.fetchone()
            if row != (SCHEMA_VERSION,):
                print(f'{db_file} is an older schema version, building fresh')
                _initialize_db(self.con)
            else:
                cached.backup(self.con)
                cached.close()

#     def make_ephemeral(self):
#         new_con = sqlite3.connect(':memory:')
#         self.con.backup(new_con)
#         self.con.close()
#         self.con = new_con

    def save_as(self, db_file: str):
        with self.con:
            cur = self.con.cursor()
            cur.execute('CREATE INDEX IF NOT EXISTS symbol_names ON symbol (name)')
            cur.execute('CREATE INDEX IF NOT EXISTS symbol_globs ON symbol_glob (pattern)')
            cur.execute('PRAGMA optimize')
        persistent = sqlite3.connect(db_file)
        self.con.backup(persistent)

    def add_partial_sdkdb(self, sdkdb_file: str):
        doc = json.load(open(sdkdb_file))

        # A partial sdkdb generated by internal tools has separate
        # SDKContentRoot and PublicSDKContentRoot sections corresponding to
        # internal and public SDKs. A sdkdb generated by InstallAPI only has
        # the former.
        root = doc['PublicSDKContentRoot' if doc['PublicSDKContentRoot']
                   else 'SDKContentRoot']
        if 'Libc' in sdkdb_file:
            import pdb; pdb.set_trace()
        with self.con:
            for ent in root:
                for category in ent.get('categories', []):
                    class_name = f'{category["interface"]}({category["name"]})'
                    self._add_objc_interface(category, class_name)
                for glob in ent.get('globals', []):
                    self._add_symbol(glob['name'], glob.get('file'))
                for iface in ent.get('interfaces', []):
                    self._add_objc_interface(iface, iface['name'])
                    self._add_objc_class(
                        iface['name'], iface.get('file'))
                for proto in ent.get('protocols', []):
                    self._add_objc_interface(proto, proto['name'])

    _method_to_selector_re = re.compile(r'[-+]\[(?P<class>\S+) '
                                        r'(?P<selector>[^\]]+)\]')

    def add_objdump(self, report: objdump.report):
        filename = report.filename
        if report.objc_class_list:
            for cls in report.objc_class_list.entries:
                if not cls.table:
                    continue
                class_name = cls.table['data', 'name']
                assert class_name, 'objdump class metadata must contain a name'
                self._add_objc_class(class_name, filename)
                if cls.metaclass:
                    self._add_symbol(f'_OBJC_METACLASS_$_{class_name}', filename)
                for method in cls.table.getall('data', 'baseMethods', 'imp'):
                    method = method
                    m = self._method_to_selector_re.match(method)
                    if m:
                        self._add_objc_selector(m.group('selector'), class_name,
                                                filename)
                    else:
                        print(f'unmatched method name: {method}')

        if report.objc_category_list:
            for cat in report.objc_category_list.entries:
                for key in ('instanceMethods', 'classMethods'):
                    for method in cat.table.getall(key, 'imp'):
                        method = method
                        m = self._method_to_selector_re.match(method)
                        if m:
                            self._add_objc_selector(m.group('selector'),
                                                    m.group('class'), filename)
                        else:
                            print(f'unmatched method name: {method}')

        if report.exports:
            for export in report.exports.entries:
                self._add_symbol(export.symbol, filename)

        self.con.commit()

    # TODO: remove?
    def add_allowlist(self, filename: str):
        allowlist = plistlib.load(open(filename, 'rb'))
        for sym in allowlist.get('symbols', ()):
            # allowlist format omits the platform prefix (_)
            if '*' in sym:
                self._add_symbol_glob(f'_{sym}', filename)
            else:
                self._add_symbol(f'_{sym}', filename)
        for cls in allowlist.get('classes', ()):
            self._add_objc_class(cls, filename)
        for sel in allowlist.get('selectors', ()):
            self._add_objc_selector(sel, None, filename)

    def symbol(self, name: str):
        cur = self.con.cursor()
        cur.execute('SELECT * FROM symbol WHERE name = ? UNION '
                    'SELECT * FROM symbol_glob WHERE ? GLOB pattern '
                    'LIMIT 1', (name, name))
        row = cur.fetchone()
        if row:
            return dict(name=row[0], file=row[1])

    def objc_class(self, name: str):
        cur = self.con.cursor()
        cur.execute('SELECT * FROM objc_class WHERE name = ?', (name,))
        row = cur.fetchone()
        if row:
            return dict(name=row[0], file=row[1])

    def objc_selector(self, selector: str):
        cur = self.con.cursor()
        cur.execute('SELECT * FROM objc_selector WHERE name = ?', (selector,))
        row = cur.fetchone()
        if row:
            return dict(name=row[0], class_name=row[1], file=row[2])

    def stats(self):
        cur = self.con.cursor()
        cur.execute('SELECT (SELECT COUNT(name) FROM symbol) AS symbol_count, '
                    '(SELECT COUNT(name) FROM objc_class) AS objc_class_count, '
                    '(SELECT COUNT(name) FROM objc_selector) AS selector_count')
        row = cur.fetchone()
        return row

    def _add_objc_interface(self, ent, class_name):
        for method in ent.get('instanceMethods', []):
            self._add_objc_selector(
                method['name'], class_name, method.get('file'))
        for prop in ent.get('properties', []):
            self._add_objc_selector(
                prop['getter'], class_name, prop.get('file'))
            if 'readonly' not in prop.get('attr', {}):
                self._add_objc_selector(
                    prop['setter'], class_name, prop.get('file'))
        for ivar in ent.get('ivars', []):
            self._add_symbol(
                f'_OBJC_IVAR_$_{class_name}.{ivar["name"]}', ivar.get('file'))

    def _add_symbol(self, name, file):
        cur = self.con.cursor()
        cur.execute('INSERT INTO symbol VALUES (?, ?)', (name, file))

    def _add_symbol_glob(self, pattern, file):
        cur = self.con.cursor()
        cur.execute('INSERT INTO symbol_glob VALUES (?, ?)', (pattern, file))

    def _add_objc_class(self, name, file):
        cur = self.con.cursor()
        cur.execute('INSERT INTO objc_class VALUES (?, ?)',
                    (name, file))
        cur.execute('INSERT INTO symbol VALUES (?, ?)',
                    (f'_OBJC_CLASS_$_{name}', file))
        cur.execute('INSERT INTO symbol VALUES (?, ?)',
                    (f'_OBJC_METACLASS_$_{name}', file))

    def _add_objc_selector(self, name, class_name, file):
        cur = self.con.cursor()
        cur.execute('INSERT INTO objc_selector VALUES (?, ?, ?)',
                    (name, class_name, file))


def _initialize_db(con: sqlite3.Connection):
    cur = con.cursor()
    cur.execute('CREATE TABLE symbol(name, file)')
    cur.execute('CREATE TABLE symbol_glob(pattern, file)')
    cur.execute('CREATE TABLE objc_class(name, file)')
    cur.execute('CREATE TABLE objc_selector(name, class, file)')
    cur.execute('CREATE TABLE meta(key, value)')
    # TODO: maybe include target tuple here?
    cur.execute('INSERT INTO meta VALUES '
                '("version", ?), ("partial_hash", NULL)',
                (SCHEMA_VERSION,))
    con.commit()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', dest='db_file')
    parser.add_argument('--allowlist')
    parser.add_argument('partial_sdkdbs', nargs='+')
    args = parser.parse_args()

    s = sdkdb()
    for sdkdb_file in args.partial_sdkdbs:
        s.add_partial_sdkdb(sdkdb_file)
    if args.allowlist:
        s.add_allowlist(args.allowlist)
    if args.db_file:
        s.save_as(args.db_file)
    symbols, classes, selectors = s.stats()
    print(f'Added {len(args.partial_sdkdbs)} sdkdb(s). {symbols=} {classes=} {selectors=}')
#     s.add_partial_sdkdb(
#         '/Volumes/Data/OpenSource/workdir/SDKDB_expected/partial.sdkdb', 'Foundation')
    print(f'{s.symbol("_NSSwapHostLongToBig")=}')
    print(f'{s.objc_class("NSString")=}')
    print(f'{s.objc_selector("stringByAppendingString:")=}')
